<?php

# database/seeds/CityTableSeeder.php

use App\Models\Base\City;
use Illuminate\Database\Seeder;

class CityTableSeeder extends Seeder  
{
    public function run()
    {
        City::create([ 'city_id' => '10000', 'city_name' => 'Banda Aceh', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10001', 'city_name' => 'Bireuen', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10002', 'city_name' => 'Blang Kejeren', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10003', 'city_name' => 'Blangpidie', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10004', 'city_name' => 'Calang', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10005', 'city_name' => 'Idi Rayeuk', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10006', 'city_name' => 'Jantho', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10007', 'city_name' => 'Krueng Sa bee', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10008', 'city_name' => 'Kuala Simpang', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10009', 'city_name' => 'Kutacane', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10010', 'city_name' => 'Langsa', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10011', 'city_name' => 'Lhokseumawe', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10012', 'city_name' => 'Lhoksukon', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10013', 'city_name' => 'Meulaboh', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10014', 'city_name' => 'Meureudu', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10015', 'city_name' => 'Sabang', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10016', 'city_name' => 'Sigh', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10017', 'city_name' => 'Simpang Tiga Redelon', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10018', 'city_name' => 'Sinabang', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10019', 'city_name' => 'Singkil', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10020', 'city_name' => 'Subulussalam', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10021', 'city_name' => 'Suka Makmue', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10022', 'city_name' => 'Takengon', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10023', 'city_name' => 'Tapak Tuan', 'airport_code' => 'BTJ', 'province_id' => '10000']);
        City::create([ 'city_id' => '10024', 'city_name' => 'Balige', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10025', 'city_name' => 'Medan Belawan', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10026', 'city_name' => 'Binjai', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10027', 'city_name' => 'Dolok Sangggul', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10028', 'city_name' => 'Gunung Sitoli', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10029', 'city_name' => 'Gunung Tua', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10030', 'city_name' => 'Kabanjahe', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10031', 'city_name' => 'Kisaran', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10033', 'city_name' => 'Limapuluh', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10034', 'city_name' => 'Lubuk Pakam', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10035', 'city_name' => 'Medan', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10036', 'city_name' => 'Padang Sidempuan', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10038', 'city_name' => 'Pangururan', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10039', 'city_name' => 'Panyambungan', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10040', 'city_name' => 'Pematang Siantar', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10041', 'city_name' => 'Rantau Prapat', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10042', 'city_name' => 'Salak', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10043', 'city_name' => 'Sei Rampah', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10044', 'city_name' => 'Sibolga', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10045', 'city_name' => 'Siborong Borong', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10046', 'city_name' => 'Sibuhuan', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10047', 'city_name' => 'Sidikalang', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10048', 'city_name' => 'Sipirok', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10049', 'city_name' => 'Stabat', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10050', 'city_name' => 'Tanjung Balai Asahan', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10051', 'city_name' => 'Tanjung Morawa', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10052', 'city_name' => 'Tarutung', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10053', 'city_name' => 'Tebing Tinggi', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10054', 'city_name' => 'Teluk Dalam', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10055', 'city_name' => 'Bagan Siapi-api', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10056', 'city_name' => 'Bangkinang', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10057', 'city_name' => 'Bengkalis', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10058', 'city_name' => 'Dumai', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10059', 'city_name' => 'Duri', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10060', 'city_name' => 'Marpoyan', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10061', 'city_name' => 'Minas', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10062', 'city_name' => 'Pangkalan Kerinci', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10063', 'city_name' => 'Pasir Pangairan', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10064', 'city_name' => 'Pekan Baru', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10065', 'city_name' => 'Rengat', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10066', 'city_name' => 'Rumbai', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10067', 'city_name' => 'Siaksriindapura', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10068', 'city_name' => 'Teluk Kuantan', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10069', 'city_name' => 'Tembilahan', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10070', 'city_name' => 'Ujung Batu', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10071', 'city_name' => 'Bandar Seri Bintan', 'airport_code' => 'TNJ', 'province_id' => '10003']);
        City::create([ 'city_id' => '10072', 'city_name' => 'Batam', 'airport_code' => 'BTH', 'province_id' => '10003']);
        City::create([ 'city_id' => '10074', 'city_name' => 'Kabil', 'airport_code' => 'BTH', 'province_id' => '10003']);
        City::create([ 'city_id' => '10075', 'city_name' => 'Daik', 'airport_code' => 'BTH', 'province_id' => '10003']);
        City::create([ 'city_id' => '10076', 'city_name' => 'Nongsa', 'airport_code' => 'BTH', 'province_id' => '10003']);
        City::create([ 'city_id' => '10077', 'city_name' => 'Ranai', 'airport_code' => 'BTH', 'province_id' => '10003']);
        City::create([ 'city_id' => '10078', 'city_name' => 'Kundur', 'airport_code' => 'BTH', 'province_id' => '10003']);
        City::create([ 'city_id' => '10079', 'city_name' => 'Tanjung Pinang', 'airport_code' => 'TNJ', 'province_id' => '10003']);
        City::create([ 'city_id' => '10080', 'city_name' => 'Arosuka', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10081', 'city_name' => 'Batu Sangkar', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10082', 'city_name' => 'Bukittinggi', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10086', 'city_name' => 'Lubuk Alung', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10087', 'city_name' => 'Lubuk Basung', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10088', 'city_name' => 'Lubuk Sikaping', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10089', 'city_name' => 'Muaro Sijunjung', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10090', 'city_name' => 'Padang', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10091', 'city_name' => 'Padang Panjang', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10093', 'city_name' => 'Painan', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10094', 'city_name' => 'Pariaman', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10095', 'city_name' => 'Payakumbuh', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10096', 'city_name' => 'Sawah Lunto', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10097', 'city_name' => 'Solok', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10099', 'city_name' => 'Tua Pejat', 'airport_code' => 'AMQ', 'province_id' => '10025']);
        City::create([ 'city_id' => '10100', 'city_name' => 'Bangko', 'airport_code' => 'DJB', 'province_id' => '10005']);
        City::create([ 'city_id' => '10101', 'city_name' => 'Jambi', 'airport_code' => 'DJB', 'province_id' => '10005']);
        City::create([ 'city_id' => '10102', 'city_name' => 'Kuala Tungkal', 'airport_code' => 'DJB', 'province_id' => '10005']);
        City::create([ 'city_id' => '10103', 'city_name' => 'Muara Bulian', 'airport_code' => 'DJB', 'province_id' => '10005']);
        City::create([ 'city_id' => '10104', 'city_name' => 'Muara Bungo', 'airport_code' => 'DJB', 'province_id' => '10005']);
        City::create([ 'city_id' => '10105', 'city_name' => 'Muara Sabak', 'airport_code' => 'DJB', 'province_id' => '10005']);
        City::create([ 'city_id' => '10106', 'city_name' => 'Muara Tebo', 'airport_code' => 'DJB', 'province_id' => '10005']);
        City::create([ 'city_id' => '10108', 'city_name' => 'Sarolangun', 'airport_code' => 'DJB', 'province_id' => '10005']);
        City::create([ 'city_id' => '10110', 'city_name' => 'Sungai Penuh', 'airport_code' => 'DJB', 'province_id' => '10005']);
        City::create([ 'city_id' => '10111', 'city_name' => 'Baturaja', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10112', 'city_name' => 'Indralaya', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10113', 'city_name' => 'Kota Kayu Agung', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10114', 'city_name' => 'Lahat', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10115', 'city_name' => 'Lubuk Linggau', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10116', 'city_name' => 'Martapura', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10117', 'city_name' => 'Muara Beliti Baru / Musi', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10118', 'city_name' => 'Muara Enim / Tanjung', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10119', 'city_name' => 'Muaradua', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10120', 'city_name' => 'Pagar Alam', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10121', 'city_name' => 'Palembang', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10122', 'city_name' => 'Pangkalan Balai', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10123', 'city_name' => 'Prabumulih', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10124', 'city_name' => 'Sekayu', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10126', 'city_name' => 'Sungai Lilin', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10127', 'city_name' => 'Tebing Tinggi', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10128', 'city_name' => 'Belinyu', 'airport_code' => 'PGK', 'province_id' => '10007']);
        City::create([ 'city_id' => '10129', 'city_name' => 'Jebus', 'airport_code' => 'PGK', 'province_id' => '10007']);
        City::create([ 'city_id' => '10130', 'city_name' => 'Kelapa', 'airport_code' => 'PGK', 'province_id' => '10007']);
        City::create([ 'city_id' => '10131', 'city_name' => 'Koba', 'airport_code' => 'PGK', 'province_id' => '10007']);
        City::create([ 'city_id' => '10132', 'city_name' => 'Manggar', 'airport_code' => 'TJQ', 'province_id' => '10007']);
        City::create([ 'city_id' => '10133', 'city_name' => 'Mentok', 'airport_code' => 'PGK', 'province_id' => '10007']);
        City::create([ 'city_id' => '10134', 'city_name' => 'Pangkal Pinang', 'airport_code' => 'PGK', 'province_id' => '10007']);
        City::create([ 'city_id' => '10135', 'city_name' => 'Sungai Liat', 'airport_code' => 'PGK', 'province_id' => '10007']);
        City::create([ 'city_id' => '10136', 'city_name' => 'Tanjung Pandan', 'airport_code' => 'TJQ', 'province_id' => '10007']);
        City::create([ 'city_id' => '10137', 'city_name' => 'Toboali', 'airport_code' => 'PGK', 'province_id' => '10007']);
        City::create([ 'city_id' => '10138', 'city_name' => 'Arga Makmur', 'airport_code' => 'BKS', 'province_id' => '10008']);
        City::create([ 'city_id' => '10139', 'city_name' => 'Bengkulu', 'airport_code' => 'BKS', 'province_id' => '10008']);
        City::create([ 'city_id' => '10140', 'city_name' => 'Curup', 'airport_code' => 'BKS', 'province_id' => '10008']);
        City::create([ 'city_id' => '10141', 'city_name' => 'Kaur', 'airport_code' => 'BKS', 'province_id' => '10008']);
        City::create([ 'city_id' => '10142', 'city_name' => 'Kepahiang', 'airport_code' => 'BKS', 'province_id' => '10008']);
        City::create([ 'city_id' => '10143', 'city_name' => 'Lebong', 'airport_code' => 'BKS', 'province_id' => '10008']);
        City::create([ 'city_id' => '10144', 'city_name' => 'Kota Manna', 'airport_code' => 'BKS', 'province_id' => '10008']);
        City::create([ 'city_id' => '10145', 'city_name' => 'Muko-muko', 'airport_code' => 'BKS', 'province_id' => '10008']);
        City::create([ 'city_id' => '10146', 'city_name' => 'Tais', 'airport_code' => 'BKS', 'province_id' => '10008']);
        City::create([ 'city_id' => '10147', 'city_name' => 'Bakauheuni', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10148', 'city_name' => 'Bandar Lampung', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10149', 'city_name' => 'Blambangan Umpu', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10150', 'city_name' => 'Bukit Kemuning', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10151', 'city_name' => 'Gedong Tataan', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10152', 'city_name' => 'Gunung Sugih', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10153', 'city_name' => 'Kalianda', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10154', 'city_name' => 'Kota Agung', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10155', 'city_name' => 'Kotabumi', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10156', 'city_name' => 'Krui / Pesisir Tengah', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10157', 'city_name' => 'Liwa', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10158', 'city_name' => 'Menggala', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10159', 'city_name' => 'Metro', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10160', 'city_name' => 'Pringsewu', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10161', 'city_name' => 'Sukadana', 'airport_code' => 'PNK', 'province_id' => '10016']);
        City::create([ 'city_id' => '10162', 'city_name' => 'Sumber Jaya', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10163', 'city_name' => 'Talang Padang', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10164', 'city_name' => 'Anyer', 'airport_code' => 'CLG', 'province_id' => '10010']);
        City::create([ 'city_id' => '10165', 'city_name' => 'Balaraja', 'airport_code' => 'TGR', 'province_id' => '10010']);
        City::create([ 'city_id' => '10166', 'city_name' => 'Baros', 'airport_code' => 'CLG', 'province_id' => '10010']);
        City::create([ 'city_id' => '10167', 'city_name' => 'Cilegon', 'airport_code' => 'CLG', 'province_id' => '10010']);
        City::create([ 'city_id' => '10168', 'city_name' => 'Merak', 'airport_code' => 'CLG', 'province_id' => '10010']);
        City::create([ 'city_id' => '10169', 'city_name' => 'Pandeglang', 'airport_code' => 'CLG', 'province_id' => '10010']);
        City::create([ 'city_id' => '10170', 'city_name' => 'Rangkasbitung', 'airport_code' => 'CLG', 'province_id' => '10010']);
        City::create([ 'city_id' => '10171', 'city_name' => 'Serang', 'airport_code' => 'CLG', 'province_id' => '10010']);
        City::create([ 'city_id' => '10172', 'city_name' => 'Tigaraksa', 'airport_code' => 'TGR', 'province_id' => '10010']);
        City::create([ 'city_id' => '10173', 'city_name' => 'Bandung', 'airport_code' => 'BDO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10174', 'city_name' => 'Banjar', 'airport_code' => 'BDO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10175', 'city_name' => 'Ciamis', 'airport_code' => 'BDO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10176', 'city_name' => 'Cianjur', 'airport_code' => 'SMI', 'province_id' => '10011']);
        City::create([ 'city_id' => '10177', 'city_name' => 'Cimahi', 'airport_code' => 'BDO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10178', 'city_name' => 'Cirebon', 'airport_code' => 'CBN', 'province_id' => '10011']);
        City::create([ 'city_id' => '10179', 'city_name' => 'Garut', 'airport_code' => 'BDO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10180', 'city_name' => 'Indramayu', 'airport_code' => 'CBN', 'province_id' => '10011']);
        City::create([ 'city_id' => '10181', 'city_name' => 'Jatibarang', 'airport_code' => 'CBN', 'province_id' => '10011']);
        City::create([ 'city_id' => '10182', 'city_name' => 'Jatinangor', 'airport_code' => 'BDO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10183', 'city_name' => 'Jatiwangi', 'airport_code' => 'CBN', 'province_id' => '10011']);
        City::create([ 'city_id' => '10184', 'city_name' => 'Kadipatin', 'airport_code' => 'CBN', 'province_id' => '10011']);
        City::create([ 'city_id' => '10185', 'city_name' => 'Karawang', 'airport_code' => 'KRW', 'province_id' => '10011']);
        City::create([ 'city_id' => '10186', 'city_name' => 'Kuningan', 'airport_code' => 'CBN', 'province_id' => '10011']);
        City::create([ 'city_id' => '10187', 'city_name' => 'Lembang', 'airport_code' => 'BDO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10188', 'city_name' => 'Losari', 'airport_code' => 'CBN', 'province_id' => '10011']);
        City::create([ 'city_id' => '10189', 'city_name' => 'Majalaya', 'airport_code' => 'BDO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10190', 'city_name' => 'Majalengka', 'airport_code' => 'CBN', 'province_id' => '10011']);
        City::create([ 'city_id' => '10191', 'city_name' => 'Ngamprah', 'airport_code' => 'BDO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10192', 'city_name' => 'Palimanan', 'airport_code' => 'CBN', 'province_id' => '10011']);
        City::create([ 'city_id' => '10193', 'city_name' => 'Purwakarta', 'airport_code' => 'BDO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10194', 'city_name' => 'Rancaekek', 'airport_code' => 'BDO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10195', 'city_name' => 'Singaparna', 'airport_code' => 'BDO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10196', 'city_name' => 'Soreang', 'airport_code' => 'BDO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10197', 'city_name' => 'Subang', 'airport_code' => 'BDO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10198', 'city_name' => 'Sukabumi', 'airport_code' => 'SMI', 'province_id' => '10011']);
        City::create([ 'city_id' => '10199', 'city_name' => 'Sumber', 'airport_code' => 'CBN', 'province_id' => '10011']);
        City::create([ 'city_id' => '10200', 'city_name' => 'Sumedang', 'airport_code' => 'BDO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10201', 'city_name' => 'Tasikmalaya', 'airport_code' => 'BDO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10202', 'city_name' => 'Ajibarang', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10203', 'city_name' => 'Ambarawa', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10204', 'city_name' => 'Banjarnegara', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10205', 'city_name' => 'Batang', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10206', 'city_name' => 'Blora', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10208', 'city_name' => 'Boyolali', 'airport_code' => 'SOC', 'province_id' => '10012']);
        City::create([ 'city_id' => '10209', 'city_name' => 'Brebes', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10210', 'city_name' => 'Bumi Ayu', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10211', 'city_name' => 'Cepu', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10212', 'city_name' => 'Cilacap', 'airport_code' => 'CXP', 'province_id' => '10012']);
        City::create([ 'city_id' => '10213', 'city_name' => 'Demak', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10214', 'city_name' => 'Jepara', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10215', 'city_name' => 'Karang Anyar', 'airport_code' => 'SOC', 'province_id' => '10012']);
        City::create([ 'city_id' => '10216', 'city_name' => 'Kartosuro', 'airport_code' => 'SOC', 'province_id' => '10012']);
        City::create([ 'city_id' => '10217', 'city_name' => 'Kebumen', 'airport_code' => 'MGL', 'province_id' => '10012']);
        City::create([ 'city_id' => '10218', 'city_name' => 'Kendal', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10219', 'city_name' => 'Klaten', 'airport_code' => 'SOC', 'province_id' => '10012']);
        City::create([ 'city_id' => '10220', 'city_name' => 'Kudus', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10221', 'city_name' => 'Magelang', 'airport_code' => 'MGL', 'province_id' => '10012']);
        City::create([ 'city_id' => '10222', 'city_name' => 'Majenang', 'airport_code' => 'CXP', 'province_id' => '10012']);
        City::create([ 'city_id' => '10223', 'city_name' => 'Mungkid', 'airport_code' => 'MGL', 'province_id' => '10012']);
        City::create([ 'city_id' => '10224', 'city_name' => 'Pati', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10225', 'city_name' => 'Pekalongan', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10226', 'city_name' => 'Pemalang', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10227', 'city_name' => 'Purbalingga', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10228', 'city_name' => 'Purwokerto', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10229', 'city_name' => 'Purwodadi', 'airport_code' => 'MGL', 'province_id' => '10012']);
        City::create([ 'city_id' => '10230', 'city_name' => 'Purworejo', 'airport_code' => 'MGL', 'province_id' => '10012']);
        City::create([ 'city_id' => '10231', 'city_name' => 'Rembang', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10232', 'city_name' => 'Salatiga', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10233', 'city_name' => 'Semarang', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10234', 'city_name' => 'Slawi', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10235', 'city_name' => 'Sragen', 'airport_code' => 'SOC', 'province_id' => '10012']);
        City::create([ 'city_id' => '10236', 'city_name' => 'Sukoharjo', 'airport_code' => 'SOC', 'province_id' => '10012']);
        City::create([ 'city_id' => '10237', 'city_name' => 'Surakarta / Solo', 'airport_code' => 'SOC', 'province_id' => '10012']);
        City::create([ 'city_id' => '10238', 'city_name' => 'Tegal', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10239', 'city_name' => 'Temanggung', 'airport_code' => 'MGL', 'province_id' => '10012']);
        City::create([ 'city_id' => '10240', 'city_name' => 'Ungaran', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10241', 'city_name' => 'Wonogiri', 'airport_code' => 'SOC', 'province_id' => '10012']);
        City::create([ 'city_id' => '10242', 'city_name' => 'Wonosobo', 'airport_code' => 'MGL', 'province_id' => '10012']);
        City::create([ 'city_id' => '10243', 'city_name' => 'Bantul', 'airport_code' => 'JOG', 'province_id' => '10013']);
        City::create([ 'city_id' => '10244', 'city_name' => 'Prambanan', 'airport_code' => 'JOG', 'province_id' => '10013']);
        City::create([ 'city_id' => '10245', 'city_name' => 'Sleman', 'airport_code' => 'JOG', 'province_id' => '10013']);
        City::create([ 'city_id' => '10246', 'city_name' => 'Wates / Kulon Progo', 'airport_code' => 'JOG', 'province_id' => '10013']);
        City::create([ 'city_id' => '10247', 'city_name' => 'Wonosari', 'airport_code' => 'JOG', 'province_id' => '10013']);
        City::create([ 'city_id' => '10248', 'city_name' => 'Yogyakarta', 'airport_code' => 'JOG', 'province_id' => '10013']);
        City::create([ 'city_id' => '10249', 'city_name' => 'Bangkalan', 'airport_code' => 'SUB', 'province_id' => '10014']);
        City::create([ 'city_id' => '10250', 'city_name' => 'Banyuwangi', 'airport_code' => 'JBR', 'province_id' => '10014']);
        City::create([ 'city_id' => '10251', 'city_name' => 'Batu', 'airport_code' => 'MXG', 'province_id' => '10014']);
        City::create([ 'city_id' => '10252', 'city_name' => 'Blitar', 'airport_code' => 'MXG', 'province_id' => '10014']);
        City::create([ 'city_id' => '10253', 'city_name' => 'Bojonegoro', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10254', 'city_name' => 'Bondowoso', 'airport_code' => 'JBR', 'province_id' => '10014']);
        City::create([ 'city_id' => '10255', 'city_name' => 'Caruban', 'airport_code' => 'MDN', 'province_id' => '10014']);
        City::create([ 'city_id' => '10256', 'city_name' => 'Gresik', 'airport_code' => 'SUB', 'province_id' => '10014']);
        City::create([ 'city_id' => '10257', 'city_name' => 'Jember', 'airport_code' => 'JBR', 'province_id' => '10014']);
        City::create([ 'city_id' => '10258', 'city_name' => 'Jombang', 'airport_code' => 'SUB', 'province_id' => '10014']);
        City::create([ 'city_id' => '10259', 'city_name' => 'Kediri', 'airport_code' => 'KDR', 'province_id' => '10014']);
        City::create([ 'city_id' => '10260', 'city_name' => 'Kepanjen', 'airport_code' => 'MXG', 'province_id' => '10014']);
        City::create([ 'city_id' => '10261', 'city_name' => 'Krasaan', 'airport_code' => 'PBL', 'province_id' => '10014']);
        City::create([ 'city_id' => '10262', 'city_name' => 'Lamongan', 'airport_code' => 'SUB', 'province_id' => '10014']);
        City::create([ 'city_id' => '10263', 'city_name' => 'Lumajang', 'airport_code' => 'PBL', 'province_id' => '10014']);
        City::create([ 'city_id' => '10264', 'city_name' => 'Madiun', 'airport_code' => 'MDN', 'province_id' => '10014']);
        City::create([ 'city_id' => '10265', 'city_name' => 'Magetan', 'airport_code' => 'MDN', 'province_id' => '10014']);
        City::create([ 'city_id' => '10266', 'city_name' => 'Malang', 'airport_code' => 'MXG', 'province_id' => '10014']);
        City::create([ 'city_id' => '10267', 'city_name' => 'Mojokerto', 'airport_code' => 'MJK', 'province_id' => '10014']);
        City::create([ 'city_id' => '10268', 'city_name' => 'Nganjuk', 'airport_code' => 'SUB', 'province_id' => '10014']);
        City::create([ 'city_id' => '10269', 'city_name' => 'Ngawi', 'airport_code' => 'MDN', 'province_id' => '10014']);
        City::create([ 'city_id' => '10270', 'city_name' => 'Pacitan', 'airport_code' => 'MDN', 'province_id' => '10014']);
        City::create([ 'city_id' => '10271', 'city_name' => 'Paiton', 'airport_code' => 'PBL', 'province_id' => '10014']);
        City::create([ 'city_id' => '10272', 'city_name' => 'Pamekasan', 'airport_code' => 'SUB', 'province_id' => '10014']);
        City::create([ 'city_id' => '10273', 'city_name' => 'Pandaan', 'airport_code' => 'PDN', 'province_id' => '10014']);
        City::create([ 'city_id' => '10274', 'city_name' => 'Pasuruan', 'airport_code' => 'PDN', 'province_id' => '10014']);
        City::create([ 'city_id' => '10275', 'city_name' => 'Ponorogo', 'airport_code' => 'MDN', 'province_id' => '10014']);
        City::create([ 'city_id' => '10276', 'city_name' => 'Probolinggo', 'airport_code' => 'PBL', 'province_id' => '10014']);
        City::create([ 'city_id' => '10277', 'city_name' => 'Sampang', 'airport_code' => 'SUB', 'province_id' => '10014']);
        City::create([ 'city_id' => '10278', 'city_name' => 'Sidoarjo', 'airport_code' => 'SUB', 'province_id' => '10014']);
        City::create([ 'city_id' => '10279', 'city_name' => 'Situbondo', 'airport_code' => 'PBL', 'province_id' => '10014']);
        City::create([ 'city_id' => '10280', 'city_name' => 'Sumenep', 'airport_code' => 'SUB', 'province_id' => '10014']);
        City::create([ 'city_id' => '10281', 'city_name' => 'Surabaya', 'airport_code' => 'SUB', 'province_id' => '10014']);
        City::create([ 'city_id' => '10282', 'city_name' => 'Trenggalek', 'airport_code' => 'SUB', 'province_id' => '10014']);
        City::create([ 'city_id' => '10283', 'city_name' => 'Tuban', 'airport_code' => 'SUB', 'province_id' => '10014']);
        City::create([ 'city_id' => '10284', 'city_name' => 'Tulung Agung', 'airport_code' => 'SUB', 'province_id' => '10014']);
        City::create([ 'city_id' => '10285', 'city_name' => 'Amlapura / Karangasem', 'airport_code' => 'DPS', 'province_id' => '10015']);
        City::create([ 'city_id' => '10286', 'city_name' => 'Bangli', 'airport_code' => 'DPS', 'province_id' => '10015']);
        City::create([ 'city_id' => '10287', 'city_name' => 'Denpasar', 'airport_code' => 'DPS', 'province_id' => '10015']);
        City::create([ 'city_id' => '10288', 'city_name' => 'Gianyar', 'airport_code' => 'DPS', 'province_id' => '10015']);
        City::create([ 'city_id' => '10290', 'city_name' => 'Jimbaran', 'airport_code' => 'DPS', 'province_id' => '10015']);
        City::create([ 'city_id' => '10291', 'city_name' => 'Kuta', 'airport_code' => 'DPS', 'province_id' => '10015']);
        City::create([ 'city_id' => '10292', 'city_name' => 'Menguwi', 'airport_code' => 'DPS', 'province_id' => '10015']);
        City::create([ 'city_id' => '10293', 'city_name' => 'Negara / Jembrana', 'airport_code' => 'DPS', 'province_id' => '10015']);
        City::create([ 'city_id' => '10294', 'city_name' => 'Ngurah Rai', 'airport_code' => 'DPS', 'province_id' => '10015']);
        City::create([ 'city_id' => '10295', 'city_name' => 'Nusa Dua', 'airport_code' => 'DPS', 'province_id' => '10015']);
        City::create([ 'city_id' => '10296', 'city_name' => 'Semarapura', 'airport_code' => 'DPS', 'province_id' => '10015']);
        City::create([ 'city_id' => '10297', 'city_name' => 'Sanur', 'airport_code' => 'DPS', 'province_id' => '10015']);
        City::create([ 'city_id' => '10298', 'city_name' => 'Singaraja / Buleleng', 'airport_code' => 'DPS', 'province_id' => '10015']);
        City::create([ 'city_id' => '10299', 'city_name' => 'Tabanan', 'airport_code' => 'DPS', 'province_id' => '10015']);
        City::create([ 'city_id' => '10300', 'city_name' => 'Bengkayang', 'airport_code' => 'PNK', 'province_id' => '10016']);
        City::create([ 'city_id' => '10301', 'city_name' => 'Ketapang', 'airport_code' => 'PNK', 'province_id' => '10016']);
        City::create([ 'city_id' => '10302', 'city_name' => 'Mempawah', 'airport_code' => 'PNK', 'province_id' => '10016']);
        City::create([ 'city_id' => '10303', 'city_name' => 'Nanga Pinoh / Melawi', 'airport_code' => 'PNK', 'province_id' => '10016']);
        City::create([ 'city_id' => '10304', 'city_name' => 'Ngabang', 'airport_code' => 'PNK', 'province_id' => '10016']);
        City::create([ 'city_id' => '10305', 'city_name' => 'Pontianak', 'airport_code' => 'PNK', 'province_id' => '10016']);
        City::create([ 'city_id' => '10306', 'city_name' => 'Putussibau', 'airport_code' => 'PNK', 'province_id' => '10016']);
        City::create([ 'city_id' => '10307', 'city_name' => 'Sambas', 'airport_code' => 'PNK', 'province_id' => '10016']);
        City::create([ 'city_id' => '10308', 'city_name' => 'Sanggau', 'airport_code' => 'PNK', 'province_id' => '10016']);
        City::create([ 'city_id' => '10309', 'city_name' => 'Sekadau Hilir', 'airport_code' => 'PNK', 'province_id' => '10016']);
        City::create([ 'city_id' => '10310', 'city_name' => 'Singkawang', 'airport_code' => 'PNK', 'province_id' => '10016']);
        City::create([ 'city_id' => '10311', 'city_name' => 'Sintang', 'airport_code' => 'PNK', 'province_id' => '10016']);
        City::create([ 'city_id' => '10312', 'city_name' => 'Sungai Raya', 'airport_code' => 'PNK', 'province_id' => '10016']);
        City::create([ 'city_id' => '10314', 'city_name' => 'Wajok', 'airport_code' => 'PNK', 'province_id' => '10016']);
        City::create([ 'city_id' => '10315', 'city_name' => 'Amuntai', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10316', 'city_name' => 'Banjarbaru', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10317', 'city_name' => 'Banjarmasin', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10318', 'city_name' => 'Barabai', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10319', 'city_name' => 'Batu Licin', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10320', 'city_name' => 'Kandangan', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10321', 'city_name' => 'Kotabaru', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10322', 'city_name' => 'Marabahan', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10323', 'city_name' => 'Martapura / Banjar', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10324', 'city_name' => 'Paringin / Balangan', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10325', 'city_name' => 'Pelaihari', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10326', 'city_name' => 'Rantau', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10328', 'city_name' => 'Tanjung', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10329', 'city_name' => 'Buntok', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10330', 'city_name' => 'Kasongan', 'airport_code' => 'PKY', 'province_id' => '10018']);
        City::create([ 'city_id' => '10331', 'city_name' => 'Kuala Kapuas', 'airport_code' => 'PKY', 'province_id' => '10018']);
        City::create([ 'city_id' => '10333', 'city_name' => 'Kuala Pembuang', 'airport_code' => 'PKY', 'province_id' => '10018']);
        City::create([ 'city_id' => '10334', 'city_name' => 'Lamandau / Nanga Bulik', 'airport_code' => 'PKY', 'province_id' => '10018']);
        City::create([ 'city_id' => '10335', 'city_name' => 'Muara Teweh', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10336', 'city_name' => 'Palangkaraya', 'airport_code' => 'PKY', 'province_id' => '10018']);
        City::create([ 'city_id' => '10337', 'city_name' => 'Pangkalan Bun', 'airport_code' => 'PKY', 'province_id' => '10018']);
        City::create([ 'city_id' => '10338', 'city_name' => 'Pulang Pisau', 'airport_code' => 'PKY', 'province_id' => '10018']);
        City::create([ 'city_id' => '10339', 'city_name' => 'Puruk Cahu', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10340', 'city_name' => 'Sampit', 'airport_code' => 'PKY', 'province_id' => '10018']);
        City::create([ 'city_id' => '10341', 'city_name' => 'Sukamara', 'airport_code' => 'PKY', 'province_id' => '10018']);
        City::create([ 'city_id' => '10342', 'city_name' => 'Tamiang Layang', 'airport_code' => 'BDJ', 'province_id' => '10017']);
        City::create([ 'city_id' => '10343', 'city_name' => 'Balikpapan', 'airport_code' => 'BPN', 'province_id' => '10019']);
        City::create([ 'city_id' => '10344', 'city_name' => 'Bontang', 'airport_code' => 'BTG', 'province_id' => '10019']);
        City::create([ 'city_id' => '10345', 'city_name' => 'Loa Kulu', 'airport_code' => 'SMD', 'province_id' => '10019']);
        City::create([ 'city_id' => '10346', 'city_name' => 'Malinau', 'airport_code' => 'TRK', 'province_id' => '10019']);
        City::create([ 'city_id' => '10347', 'city_name' => 'Muara Badak', 'airport_code' => 'SMD', 'province_id' => '10019']);
        City::create([ 'city_id' => '10348', 'city_name' => 'Nunukan', 'airport_code' => 'TRK', 'province_id' => '10019']);
        City::create([ 'city_id' => '10349', 'city_name' => 'Palaran', 'airport_code' => 'SMD', 'province_id' => '10019']);
        City::create([ 'city_id' => '10350', 'city_name' => 'Penaja', 'airport_code' => 'BPN', 'province_id' => '10019']);
        City::create([ 'city_id' => '10351', 'city_name' => 'Samarinda', 'airport_code' => 'SMD', 'province_id' => '10019']);
        City::create([ 'city_id' => '10352', 'city_name' => 'Sanga Sanga', 'airport_code' => 'SMD', 'province_id' => '10019']);
        City::create([ 'city_id' => '10353', 'city_name' => 'Sanggata', 'airport_code' => 'BTG', 'province_id' => '10019']);
        City::create([ 'city_id' => '10354', 'city_name' => 'Sebatik', 'airport_code' => 'TRK', 'province_id' => '10019']);
        City::create([ 'city_id' => '10355', 'city_name' => 'Sendawar', 'airport_code' => 'SMD', 'province_id' => '10019']);
        City::create([ 'city_id' => '10356', 'city_name' => 'Tanah Grogot', 'airport_code' => 'BPN', 'province_id' => '10019']);
        City::create([ 'city_id' => '10357', 'city_name' => 'Tanjung Redep / Berau', 'airport_code' => 'BPN', 'province_id' => '10019']);
        City::create([ 'city_id' => '10358', 'city_name' => 'Tanjung Selor', 'airport_code' => 'TRK', 'province_id' => '10019']);
        City::create([ 'city_id' => '10359', 'city_name' => 'Tarakan', 'airport_code' => 'TRK', 'province_id' => '10019']);
        City::create([ 'city_id' => '10360', 'city_name' => 'Teluk Pandan', 'airport_code' => 'BTG', 'province_id' => '10019']);
        City::create([ 'city_id' => '10361', 'city_name' => 'Tenggarong', 'airport_code' => 'SMD', 'province_id' => '10019']);
        City::create([ 'city_id' => '10362', 'city_name' => 'Ampana / Tojo Una Una', 'airport_code' => 'PLW', 'province_id' => '10020']);
        City::create([ 'city_id' => '10363', 'city_name' => 'Banawa / Donggala', 'airport_code' => 'PLW', 'province_id' => '10020']);
        City::create([ 'city_id' => '10364', 'city_name' => 'Banggai', 'airport_code' => 'PLW', 'province_id' => '10020']);
        City::create([ 'city_id' => '10365', 'city_name' => 'Bungku / Kolonedale', 'airport_code' => 'PLW', 'province_id' => '10020']);
        City::create([ 'city_id' => '10366', 'city_name' => 'Buol', 'airport_code' => 'PLW', 'province_id' => '10020']);
        City::create([ 'city_id' => '10367', 'city_name' => 'Tolitoli', 'airport_code' => 'PLW', 'province_id' => '10020']);
        City::create([ 'city_id' => '10368', 'city_name' => 'Luwuk', 'airport_code' => 'PLW', 'province_id' => '10020']);
        City::create([ 'city_id' => '10369', 'city_name' => 'Palu', 'airport_code' => 'PLW', 'province_id' => '10020']);
        City::create([ 'city_id' => '10370', 'city_name' => 'Parigi', 'airport_code' => 'PLW', 'province_id' => '10020']);
        City::create([ 'city_id' => '10371', 'city_name' => 'Poso', 'airport_code' => 'PLW', 'province_id' => '10020']);
        City::create([ 'city_id' => '10372', 'city_name' => 'Bantaeng', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10373', 'city_name' => 'Barru', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10374', 'city_name' => 'Belopa', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10375', 'city_name' => 'Benteng', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10376', 'city_name' => 'Bulukumba', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10377', 'city_name' => 'Enrekang', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10378', 'city_name' => 'Jeneponto', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10379', 'city_name' => 'Takalar', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10380', 'city_name' => 'Makale', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10381', 'city_name' => 'Makassar', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10382', 'city_name' => 'Malili', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10383', 'city_name' => 'Maros', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10384', 'city_name' => 'Masamba', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10385', 'city_name' => 'Palopo', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10386', 'city_name' => 'Pangkajene', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10387', 'city_name' => 'Sidenreng', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10388', 'city_name' => 'Pare - pare', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10389', 'city_name' => 'Pinrang', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10390', 'city_name' => 'Sengkang', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10391', 'city_name' => 'Sinjai', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10392', 'city_name' => 'Sungguminasa', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10393', 'city_name' => 'Watampone', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10394', 'city_name' => 'Watansoppeng', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10395', 'city_name' => 'Soroako', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10396', 'city_name' => 'Bau-Bau', 'airport_code' => 'KDI', 'province_id' => '10022']);
        City::create([ 'city_id' => '10397', 'city_name' => 'Kendari', 'airport_code' => 'KDI', 'province_id' => '10022']);
        City::create([ 'city_id' => '10398', 'city_name' => 'Kolaka', 'airport_code' => 'KDI', 'province_id' => '10022']);
        City::create([ 'city_id' => '10399', 'city_name' => 'Lasusua', 'airport_code' => 'KDI', 'province_id' => '10022']);
        City::create([ 'city_id' => '10400', 'city_name' => 'Pasar Wajo', 'airport_code' => 'KDI', 'province_id' => '10022']);
        City::create([ 'city_id' => '10401', 'city_name' => 'Raha', 'airport_code' => 'KDI', 'province_id' => '10022']);
        City::create([ 'city_id' => '10402', 'city_name' => 'Rumbia', 'airport_code' => 'KDI', 'province_id' => '10022']);
        City::create([ 'city_id' => '10403', 'city_name' => 'Unaaha', 'airport_code' => 'KDI', 'province_id' => '10022']);
        City::create([ 'city_id' => '10404', 'city_name' => 'Wanggodo / Andolo', 'airport_code' => 'KDI', 'province_id' => '10022']);
        City::create([ 'city_id' => '10405', 'city_name' => 'Wangi-Wangi / Wakatobi', 'airport_code' => 'KDI', 'province_id' => '10022']);
        City::create([ 'city_id' => '10408', 'city_name' => 'Bitung', 'airport_code' => 'MDC', 'province_id' => '10023']);
        City::create([ 'city_id' => '10410', 'city_name' => 'Kotamubagu', 'airport_code' => 'MDC', 'province_id' => '10023']);
        City::create([ 'city_id' => '10411', 'city_name' => 'Manado', 'airport_code' => 'MDC', 'province_id' => '10023']);
        City::create([ 'city_id' => '10412', 'city_name' => 'Ratahan', 'airport_code' => 'MDC', 'province_id' => '10023']);
        City::create([ 'city_id' => '10413', 'city_name' => 'Tahuna', 'airport_code' => 'MDC', 'province_id' => '10023']);
        City::create([ 'city_id' => '10414', 'city_name' => 'Tomohon', 'airport_code' => 'MDC', 'province_id' => '10023']);
        City::create([ 'city_id' => '10415', 'city_name' => 'Tondano', 'airport_code' => 'MDC', 'province_id' => '10023']);
        City::create([ 'city_id' => '10416', 'city_name' => 'Majene', 'airport_code' => 'UPG', 'province_id' => '10024']);
        City::create([ 'city_id' => '10417', 'city_name' => 'Mamasa', 'airport_code' => 'UPG', 'province_id' => '10024']);
        City::create([ 'city_id' => '10418', 'city_name' => 'Mamuju', 'airport_code' => 'UPG', 'province_id' => '10024']);
        City::create([ 'city_id' => '10419', 'city_name' => 'Pasangkayu', 'airport_code' => 'UPG', 'province_id' => '10024']);
        City::create([ 'city_id' => '10420', 'city_name' => 'Polewali', 'airport_code' => 'UPG', 'province_id' => '10024']);
        City::create([ 'city_id' => '10421', 'city_name' => 'Gorontalo', 'airport_code' => 'GTO', 'province_id' => '10032']);
        City::create([ 'city_id' => '10422', 'city_name' => 'Kwandang', 'airport_code' => 'GTO', 'province_id' => '10032']);
        City::create([ 'city_id' => '10423', 'city_name' => 'Limboto', 'airport_code' => 'GTO', 'province_id' => '10032']);
        City::create([ 'city_id' => '10424', 'city_name' => 'Marisa', 'airport_code' => 'GTO', 'province_id' => '10032']);
        City::create([ 'city_id' => '10425', 'city_name' => 'Suwawa', 'airport_code' => 'GTO', 'province_id' => '10032']);
        City::create([ 'city_id' => '10426', 'city_name' => 'Tilamuta', 'airport_code' => 'GTO', 'province_id' => '10032']);
        City::create([ 'city_id' => '10427', 'city_name' => 'Ambon', 'airport_code' => 'AMQ', 'province_id' => '10025']);
        City::create([ 'city_id' => '10428', 'city_name' => 'Dataran Hunimoa', 'airport_code' => 'AMQ', 'province_id' => '10025']);
        City::create([ 'city_id' => '10429', 'city_name' => 'Dobo', 'airport_code' => 'AMQ', 'province_id' => '10025']);
        City::create([ 'city_id' => '10431', 'city_name' => 'Namlea', 'airport_code' => 'AMQ', 'province_id' => '10025']);
        City::create([ 'city_id' => '10432', 'city_name' => 'Piru', 'airport_code' => 'AMQ', 'province_id' => '10025']);
        City::create([ 'city_id' => '10433', 'city_name' => 'Saumlaki', 'airport_code' => 'AMQ', 'province_id' => '10025']);
        City::create([ 'city_id' => '10434', 'city_name' => 'Tual', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10435', 'city_name' => 'Jailolo', 'airport_code' => 'TTE', 'province_id' => '10026']);
        City::create([ 'city_id' => '10436', 'city_name' => 'Labuha', 'airport_code' => 'TTE', 'province_id' => '10026']);
        City::create([ 'city_id' => '10437', 'city_name' => 'Maba', 'airport_code' => 'TTE', 'province_id' => '10026']);
        City::create([ 'city_id' => '10438', 'city_name' => 'Sanana', 'airport_code' => 'TTE', 'province_id' => '10026']);
        City::create([ 'city_id' => '10439', 'city_name' => 'Ternate', 'airport_code' => 'TTE', 'province_id' => '10026']);
        City::create([ 'city_id' => '10440', 'city_name' => 'Tidore', 'airport_code' => 'TTE', 'province_id' => '10026']);
        City::create([ 'city_id' => '10441', 'city_name' => 'Tobelo', 'airport_code' => 'TTE', 'province_id' => '10026']);
        City::create([ 'city_id' => '10442', 'city_name' => 'Weda / Soasiu', 'airport_code' => 'TTE', 'province_id' => '10026']);
        City::create([ 'city_id' => '10444', 'city_name' => 'Bima', 'airport_code' => 'AMI', 'province_id' => '10027']);
        City::create([ 'city_id' => '10445', 'city_name' => 'Dompu', 'airport_code' => 'AMI', 'province_id' => '10027']);
        City::create([ 'city_id' => '10446', 'city_name' => 'Gerung', 'airport_code' => 'AMI', 'province_id' => '10027']);
        City::create([ 'city_id' => '10447', 'city_name' => 'Mataram', 'airport_code' => 'AMI', 'province_id' => '10027']);
        City::create([ 'city_id' => '10448', 'city_name' => 'Praya', 'airport_code' => 'AMI', 'province_id' => '10027']);
        City::create([ 'city_id' => '10449', 'city_name' => 'Selong', 'airport_code' => 'AMI', 'province_id' => '10027']);
        City::create([ 'city_id' => '10450', 'city_name' => 'Sumbawa Besar', 'airport_code' => 'AMI', 'province_id' => '10027']);
        City::create([ 'city_id' => '10451', 'city_name' => 'Taliwang', 'airport_code' => 'AMI', 'province_id' => '10027']);
        City::create([ 'city_id' => '10452', 'city_name' => 'Woha', 'airport_code' => 'AMI', 'province_id' => '10027']);
        City::create([ 'city_id' => '10453', 'city_name' => 'Atambua', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10454', 'city_name' => 'Baa', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10455', 'city_name' => 'Bajawa', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10456', 'city_name' => 'Borong', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10457', 'city_name' => 'Ende', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10458', 'city_name' => 'Kefamenanu', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10459', 'city_name' => 'Kalabahi', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10460', 'city_name' => 'Kupang', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10461', 'city_name' => 'Labuan Bajo', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10462', 'city_name' => 'Larantuka', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10464', 'city_name' => 'Maumere', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10465', 'city_name' => 'Mbay', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10466', 'city_name' => 'Oelamasi', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10467', 'city_name' => 'Ruteng', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10468', 'city_name' => 'Soe', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10469', 'city_name' => 'Tambolaka', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10470', 'city_name' => 'Waibakul', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10471', 'city_name' => 'Waikabubak', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10472', 'city_name' => 'Waingapu', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10473', 'city_name' => 'Bintuni', 'airport_code' => 'SOQ', 'province_id' => '10029']);
        City::create([ 'city_id' => '10474', 'city_name' => 'Fak-Fak', 'airport_code' => 'SOQ', 'province_id' => '10029']);
        City::create([ 'city_id' => '10475', 'city_name' => 'Kaimana', 'airport_code' => 'SOQ', 'province_id' => '10029']);
        City::create([ 'city_id' => '10476', 'city_name' => 'Manokwari', 'airport_code' => 'SOQ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10478', 'city_name' => 'Sorong', 'airport_code' => 'SOQ', 'province_id' => '10029']);
        City::create([ 'city_id' => '10479', 'city_name' => 'Tembaga Pura', 'airport_code' => 'TIM', 'province_id' => '10030']);
        City::create([ 'city_id' => '10480', 'city_name' => 'Teminabuan', 'airport_code' => 'SOQ', 'province_id' => '10029']);
        City::create([ 'city_id' => '10481', 'city_name' => 'Timika', 'airport_code' => 'TIM', 'province_id' => '10030']);
        City::create([ 'city_id' => '10482', 'city_name' => 'Waisai', 'airport_code' => 'SOQ', 'province_id' => '10029']);
        City::create([ 'city_id' => '10483', 'city_name' => 'Agats', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10484', 'city_name' => 'Biak', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10485', 'city_name' => 'Botawa', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10486', 'city_name' => 'Jayapura', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10487', 'city_name' => 'Mulia', 'airport_code' => 'NBX', 'province_id' => '10030']);
        City::create([ 'city_id' => '10488', 'city_name' => 'Merauke', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10489', 'city_name' => 'Nabire', 'airport_code' => 'NBX', 'province_id' => '10030']);
        City::create([ 'city_id' => '10490', 'city_name' => 'Oksibil', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10491', 'city_name' => 'Sarmi', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10492', 'city_name' => 'Sorendiweri', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10493', 'city_name' => 'Sumohai', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10495', 'city_name' => 'Wamena', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10496', 'city_name' => 'Waris', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10498', 'city_name' => 'Pania / Enarotali', 'airport_code' => 'NBX', 'province_id' => '10030']);
        City::create([ 'city_id' => '10499', 'city_name' => 'Yapen Waropen / Serui', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10500', 'city_name' => 'Sentani', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10501', 'city_name' => 'Mamberamo / Burmeso', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10502', 'city_name' => 'Boven Digul / Tanah Merah', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10534', 'city_name' => 'Jakarta Utara', 'airport_code' => 'CGK', 'province_id' => '10031']);
        City::create([ 'city_id' => '10535', 'city_name' => 'Jakarta Barat', 'airport_code' => 'CGK', 'province_id' => '10031']);
        City::create([ 'city_id' => '10536', 'city_name' => 'Jakarta Selatan', 'airport_code' => 'CGK', 'province_id' => '10031']);
        City::create([ 'city_id' => '10537', 'city_name' => 'Jakarta Timur', 'airport_code' => 'CGK', 'province_id' => '10031']);
        City::create([ 'city_id' => '10539', 'city_name' => 'Abepura', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10540', 'city_name' => 'Babalan', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10541', 'city_name' => 'Banyumas', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10542', 'city_name' => 'Bekasi', 'airport_code' => 'BKI', 'province_id' => '10011']);
        City::create([ 'city_id' => '10543', 'city_name' => 'Binjai Kota', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10544', 'city_name' => 'Bogor', 'airport_code' => 'BOO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10545', 'city_name' => 'Bojongmangu', 'airport_code' => 'BKI', 'province_id' => '10011']);
        City::create([ 'city_id' => '10546', 'city_name' => 'Cabangbungin', 'airport_code' => 'BKI', 'province_id' => '10011']);
        City::create([ 'city_id' => '10547', 'city_name' => 'Cibinong', 'airport_code' => 'BOO', 'province_id' => '10011']);
        City::create([ 'city_id' => '10548', 'city_name' => 'Cikarang', 'airport_code' => 'BKI', 'province_id' => '10011']);
        City::create([ 'city_id' => '10549', 'city_name' => 'Cisoka', 'airport_code' => 'TGR', 'province_id' => '10010']);
        City::create([ 'city_id' => '10550', 'city_name' => 'Depok', 'airport_code' => 'DPK', 'province_id' => '10011']);
        City::create([ 'city_id' => '10551', 'city_name' => 'Jambe', 'airport_code' => 'TGR', 'province_id' => '10010']);
        City::create([ 'city_id' => '10552', 'city_name' => 'Jayanti', 'airport_code' => 'TGR', 'province_id' => '10010']);
        City::create([ 'city_id' => '10553', 'city_name' => 'Kademangan', 'airport_code' => 'PBL', 'province_id' => '10014']);
        City::create([ 'city_id' => '10554', 'city_name' => 'Kamu', 'airport_code' => 'NBX', 'province_id' => '10030']);
        City::create([ 'city_id' => '10555', 'city_name' => 'Karubaga', 'airport_code' => 'DJJ', 'province_id' => '10030']);
        City::create([ 'city_id' => '10556', 'city_name' => 'Kemiri', 'airport_code' => 'TGR', 'province_id' => '10010']);
        City::create([ 'city_id' => '10557', 'city_name' => 'Kepi', 'airport_code' => 'NBX', 'province_id' => '10030']);
        City::create([ 'city_id' => '10559', 'city_name' => 'Kota Masohi', 'airport_code' => 'AMQ', 'province_id' => '10025']);
        City::create([ 'city_id' => '10560', 'city_name' => 'Kresek', 'airport_code' => 'TGR', 'province_id' => '10010']);
        City::create([ 'city_id' => '10561', 'city_name' => 'Kronjo', 'airport_code' => 'TGR', 'province_id' => '10010']);
        City::create([ 'city_id' => '10562', 'city_name' => 'Kubu Raya', 'airport_code' => 'PNK', 'province_id' => '10016']);
        City::create([ 'city_id' => '10563', 'city_name' => 'Lawang Kidul', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10564', 'city_name' => 'Lembata', 'airport_code' => 'KOE', 'province_id' => '10028']);
        City::create([ 'city_id' => '10565', 'city_name' => 'Meranti', 'airport_code' => 'PKU', 'province_id' => '10002']);
        City::create([ 'city_id' => '10567', 'city_name' => 'Padang Aro', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10568', 'city_name' => 'Pagai Selatan', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10569', 'city_name' => 'Pagai Utara', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10570', 'city_name' => 'Pakuhaji', 'airport_code' => 'TGR', 'province_id' => '10010']);
        City::create([ 'city_id' => '10571', 'city_name' => 'Panongan', 'airport_code' => 'TGR', 'province_id' => '10010']);
        City::create([ 'city_id' => '10572', 'city_name' => 'Pariaman Selatan', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10573', 'city_name' => 'Pariaman Tengah', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10574', 'city_name' => 'Pariaman Utara', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10575', 'city_name' => 'Pebayuran', 'airport_code' => 'BKI', 'province_id' => '10011']);
        City::create([ 'city_id' => '10576', 'city_name' => 'Pelabuhan Ratu', 'airport_code' => 'SMI', 'province_id' => '10011']);
        City::create([ 'city_id' => '10577', 'city_name' => 'Pematang Raya', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10578', 'city_name' => 'Plaju', 'airport_code' => 'PLM', 'province_id' => '10006']);
        City::create([ 'city_id' => '10579', 'city_name' => 'Pulau Punjung', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10580', 'city_name' => 'Purwodadi ', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10581', 'city_name' => 'Rantepao', 'airport_code' => 'UPG', 'province_id' => '10021']);
        City::create([ 'city_id' => '10582', 'city_name' => 'Rasei', 'airport_code' => 'SOQ', 'province_id' => '10029']);
        City::create([ 'city_id' => '10583', 'city_name' => 'Rembang ', 'airport_code' => 'SRG', 'province_id' => '10012']);
        City::create([ 'city_id' => '10584', 'city_name' => 'Sarilamak', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10586', 'city_name' => 'Sengeti', 'airport_code' => 'DJB', 'province_id' => '10005']);
        City::create([ 'city_id' => '10587', 'city_name' => 'Serpong', 'airport_code' => 'TGR', 'province_id' => '10010']);
        City::create([ 'city_id' => '10588', 'city_name' => 'Simpang Empat', 'airport_code' => 'PDG', 'province_id' => '10004']);
        City::create([ 'city_id' => '10589', 'city_name' => 'Singkep', 'airport_code' => 'BTH', 'province_id' => '10003']);
        City::create([ 'city_id' => '10590', 'city_name' => 'Sugapa', 'airport_code' => 'NBX', 'province_id' => '10030']);
        City::create([ 'city_id' => '10591', 'city_name' => 'Sukadana ', 'airport_code' => 'TKG', 'province_id' => '10009']);
        City::create([ 'city_id' => '10592', 'city_name' => 'Sukadiri', 'airport_code' => 'TGR', 'province_id' => '10010']);
        City::create([ 'city_id' => '10593', 'city_name' => 'Sukatani', 'airport_code' => 'BKI', 'province_id' => '10011']);
        City::create([ 'city_id' => '10594', 'city_name' => 'Sukawangi', 'airport_code' => 'BKI', 'province_id' => '10011']);
        City::create([ 'city_id' => '10595', 'city_name' => 'Tanah Tidung', 'airport_code' => 'TRK', 'province_id' => '10019']);
        City::create([ 'city_id' => '10596', 'city_name' => 'Tangerang', 'airport_code' => 'TGR', 'province_id' => '10010']);
        City::create([ 'city_id' => '10597', 'city_name' => 'Tanjung Balai', 'airport_code' => 'MES', 'province_id' => '10001']);
        City::create([ 'city_id' => '10598', 'city_name' => 'Tigi', 'airport_code' => 'NBX', 'province_id' => '10030']);
        City::create([ 'city_id' => '10599', 'city_name' => 'Wlingi', 'airport_code' => 'MXG', 'province_id' => '10014']);
        City::create([ 'city_id' => '10601', 'city_name' => 'Jakarta Pusat', 'airport_code' => 'CGK', 'province_id' => '10031']);
        City::create([ 'city_id' => '10603', 'city_name' => 'Lombok', 'airport_code' => 'AMI', 'province_id' => '10027']);
        City::create([ 'city_id' => '10604', 'city_name' => 'Manado', 'airport_code' => 'MDC', 'province_id' => '10023' ]);

        //... add more Citys if you want!
    }
}
